name: build
jobs:
  build:
    runs-on: steden88/cicd:1.0 # 工作流运行的环境
    steps:
      - name: 开启Git代理
        uses: gitProxy@v1
        with:
          proxy: "socks5://192.168.1.88:7890"
        #run: git config --global http.https://github.com.proxy socks5://192.168.1.88:7890 && git config --global https.https://github.com.proxy socks5://192.168.1.88:7890
      - name: Git clone # 拉取Git
        uses: farseers/FOPS-Actions/checkout@v1
        with:
          repository: https://github.com/farseers/FOPS.git
          branch: main
          username: test
          password: 123456
          path: fops
      - name: Login docker # 登陆镜像
        uses: dockerLogin@v1

      - name: Build Dockerfile # 制作dockerfile
        uses: dockerfile@v1

      - name: Build Docker # 打包镜像
        uses: dockerBuild@v1

      - name: Upload Docker # 上传镜像
        uses: dockerUpload@v1

      - name: Update ImageVer # 更新镜像
        uses: dockerswarmUpdateVer@v1

        run: go build