name: build
jobs:
  build:
    runs-on: steden88/cicd:1.0 # 工作流运行的环境
    steps:
      - name: 开启Git代理
        uses: gitProxy@v1
        with:
          proxy: "socks5://192.168.1.88:7890"

      - name: 拉取应用Git
        uses: checkout@v1

      - name: 拉取框架fs
        uses: checkout@v1
        with:
          hub: https://github.com/farseer-go/fs.git
          branch: main
          username: test
          password: 123456
          path: farseer-go/fs

#      - name: Login docker # 登陆镜像
#        uses: dockerLogin@v1

      - name: Build Docker # 打包镜像
        uses: dockerBuild@v1

      - name: Upload Docker # 上传镜像
        uses: dockerUpload@v1

      - name: Update ImageVer # 更新镜像
        uses: dockerswarmUpdateVer@v1

        run: go build